# MOD - Grafana - Ingress
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - grafana.localhost
  path: /
  pathType: ImplementationSpecific

# MOD - Grafana - Admin User
adminUser: taygun
# MOD - Grafana - Admin Password
adminPassword: taygun

# MOD - Grafana - Persistence
persistence:
  enabled: true
  size: 1Gi